import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Providers from '@/lib/providers'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={cn('h-full', 'antialiased', 'font-sans', figtree.variable)}>
      <Providers>
        <body className="min-h-full flex flex-col">
          <Header />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  )
}
